apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper-asr-webservice
  namespace: whisper-asr-webservice
spec:
  releaseName: whisper-asr-webservice
  chart:
    spec:
      chart: whisper-asr-webservice
      sourceRef:
        kind: HelmRepository
        name: whisper-asr-webservice
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ASR_MODEL: large-v2
                ASR_ENGINE: openai_whisper